### ISSUE TITLE
Path to v2.0

### ISSUE THREAD

**Issue by bkintanar** [PokemonTCG/pokemon-tcg-sdk-php#9]
We'll try do detail specific things to that needed to be done here for the package to support v2.0 of the API.

We can talk about what new technology that we can use and how to improve the current sdk. Talking about using a framework or a library to hasten the development is welcome as well.

**Comment by mmonkey** [comment]
### Overview
In order to support v2, the following changes must be supported. [See the official documentation for more details](https://docs.pokemontcg.io/#documentationmigration). I propose the architecture remains the same while v2 is implemented.

### General
- [ ] Update PHP requirement to [supported versions](https://www.php.net/supported-versions.php) - `7.4` & `8.0`
- [ ] Add support for `X-Api-Key` header
- [ ] Response data now lives inside a `data` field instead of `cards` , `sets`, `subtypes`, etc

### Pagination
- [ ] Support `page` and `pageSize` for requests
- [ ] Support `page`, `pageSize`, `count` and `totalCount` in responses

### Cards
- [ ] Replace `subtype` with `subtypes` array
- [ ] Replace `ability` with `abilities` array
- [ ] Replace `nationalPokedexNumber` with `nationalPokedexNumbers` array
- [ ] Replace `imageUrl` and `imageHiRes` with `images` object
- [ ] Replace `text` with `rules`
- [ ] Add `legalities` object
- [ ] Add `tcgplayer` object
- [ ] Add `set` object
- [ ] Add `flavorText` string
- [ ] Add `evolvesTo` array

### Sets
- [ ] Replace `standardLegal` and `expandedLegal` with `legalities` object
- [ ] Replace `totalCards` with `printedTotal`
- [ ] Replace `symbolUrl` and `logoUrl` with `logos` object
- [ ] Add `total` number
